fs = 200;
N =  400;
t = (0:(N-1))/fs; 
s1 = sin(2*pi*10*t);
s2 = sin(2*pi*20*t);
s = [s1 s2];
t = (0:length(s)-1)/fs;
v = 2*randn(size(t));  
x = s+v;
	
L = 256;
mu = 0.0001;
[y,e,b] = lms(x,s,mu,L);
a = 1;
figure(341);
subplot(2,1,1), plot(t,y);
title('Відфільтрований сигнал y(n) для L = 256');
xlabel('Час'), ylabel('Амплітуда');
n = 512;
[h, w] = freqz(b,a,n);
mag = abs(h);
subplot(2,1,2), plot(w/(2*pi)*fs, mag);
title('АЧХ для L = 256');
xlabel('Частота'), ylabel('Амплітуда');

fs = 200;
N =  800;
t = (0:(N-1))/fs; 
s1 = sin(2*pi*10*t);
s2 = sin(2*pi*20*t);
s = [s1 s2];
t = (0:length(s)-1)/fs;
v = 2*randn(size(t));  
x = s+v;

L = 512;
mu = 0.0001;
[y,e,b] = lms(x,s,mu,L);
a = 1;
figure(342);
subplot(2,1,1), plot(t,y);
title('Відфільтрований сигнал y(n) для L = 512');
xlabel('Час'), ylabel('Амплітуда');
n = 512;
[h, w] = freqz(b,a,n);
mag = abs(h);
subplot(2,1,2), plot(w/(2*pi)*fs, mag);
title('АЧХ для L = 512');
xlabel('Частота'), ylabel('Амплітуда');

fs = 200;
N =  2000;
t = (0:(N-1))/fs; 
s1 = sin(2*pi*10*t);
s2 = sin(2*pi*20*t);
s = [s1 s2];
t = (0:length(s)-1)/fs;
v = 2*randn(size(t));  
x = s+v;

L = 1024;
mu = 0.0001;
[y,e,b] = lms(x,s,mu,L);
a = 1;
figure(343);
subplot(2,1,1), plot(t,y);
title('Відфільтрований сигнал y(n) для L = 1024');
xlabel('Час'), ylabel('Амплітуда');
n = 512;
[h, w] = freqz(b,a,n);
mag = abs(h);
subplot(2,1,2), plot(w/(2*pi)*fs, mag);
title('АЧХ для L = 1024');
xlabel('Частота'), ylabel('Амплітуда');